before_install:
- gem install bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  chrome: stable
env:
  global:
  - PGPORT=5433
dist: xenial
script:
- yarn
- bundle exec rails db:reset RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: e9wh59zs5WpJCDOI/B5QPyQC8U0cvU1ZGIbRvx6w4wuj5sCK//M7VDRsyLUZW6eskMMMGrLs83WsvUgKo+qt0mSjFPZAeGNOA6JDzPVgELi6ySPUqzyVu6N+n592WKZ4fSemFL0nhD93g+MSUkFmDfj6BwJq47Fo61OOClYLrNVPtDDu26pBbv9hQagJbWvJ3iD7JYIR+M1TC/oVLSrG1maLA1rdQZSpbLx1H+hNZM0TVAF8jv6gvT5z/LcJ4j0RsWRhzrh4vmR2Rq9284ivb8bUYI8kigVolm7RssKWVXcGao3bM6XS9NFf/SMpxESqLIUDuttEI4UNPktILgvM5z1KVY0o8EJF449vWpu6J6uFn6x1nHrhTeZN3IZfXCjODKNXzGvfSGWM0zu5Fb/XxVBZdDWjwtdJvUzt7la0GBGHzfGoAkJvmep4z4BuOKnEJl960V9uoRmvX9R46bVPt8ClP10ywhzzUx963fRUL3n/48qWRSvYndYEAXvDcSQKo+nXlXFfkEHJeDdyHp6qh4GdlBnXVuBlz0FRq5yR9Q/0Fg3imXJJTtbpcU8Rmiy1f2in5uuxnn2pBfryj2zPfZvku0bc1E5cYa7R7CXaEyhvxuFj6VaUkZWCf5KF49JI7VV/ZV4hyWDelDuDTxNkGWLvN++RG51MCN2Lg/+AGQg=
  app: tandem-trivia-quiz
  run:
    - rails db:migrate
    - rake seed
  on:
    branch: main
notifications:
  email: false